### ISSUE TITLE
Structurizr.PlantUML uses "Software System" as tag although I added one myself.

### ISSUE THREAD

**Issue by niem94** [structurizr/dotnet-extensions#1]
Code that adds a tag, fx "Intermediary"
<img width="813" alt="image" src="https://user-images.githubusercontent.com/26203420/73649180-825ac880-467f-11ea-925b-5ffeb6a18133.png">

Resulting plantUML Diagram:
![image](https://user-images.githubusercontent.com/26203420/73649424-0b71ff80-4680-11ea-8649-a9322d5d9140.png)

Expected result:
I expect the Added Tag to be used in the PlantUML Diagram, so It does not write "Software System", but fx. "Intermediary".

**Comment by simonbrowndotje** [comment]
I've had a look at this, and it's by design that the PlantUML writer uses the type of the element as the UML stereotype. I'd be happy to make a change so that the terminology you set in the workspace (https://github.com/structurizr/dotnet/blob/master/Structurizr.Core/View/Terminology.cs) is reflected in the PlantUML definition. This would allow you to change all occurrences of "Software System" to another phrase. Does that work?

**Comment by niem94** [comment]
@simonbrowndotje sadly that is not what i am looking for. In my case the components act as stakeholders, and the UML stereotype is required to reflect the type of stakeholder fx "Intermediary", "Customer" or "Supplier". Therefore having control of their individual UML stereotype is important for me. 
Is this something you would be able to accommodate, or guide me in implementing a PR for?

**Comment by simonbrowndotje** [comment]
I've made the ```TypeOf()``` method public and virtual, so that you can override it to do whatever you need. For example:

```
class MyPlantUMLWriter : PlantUMLWriter
{
    public override string TypeOf(Element e)
    {
        return e.Tags...;
    }
}
```

If you're building the extensions library yourself, you can use this now. Otherwise it will be available in the next release.

**Comment by niem94** [comment]
Awesome @simonbrowndotje, thank you a lot. I'll wait for the release or now, and grab the source code when I get back to that issue :-)

**Comment by niem94** [comment]
@simonbrowndotje would this be something you would consider to support for the cloud model aswell?

**Comment by simonbrowndotje** [comment]
You can use the [Terminology](https://github.com/structurizr/dotnet/blob/master/Structurizr.Core/View/Terminology.cs) class (workspace.Model.Views.Configuration.Terminology) to customise the terminology used when rendering the diagrams, but this applies to all diagrams within a workspace.

**Comment by niem94** [comment]
@simonbrowndotje i don't think this allows me to set a custom terminology for individual software systems. If so I am not sure how, as setting the following sets the terminology for all software systems:

```cs
Terminology terminology = Workspace.Views.Configuration.Terminology;
terminology.SoftwareSystem = stakeholders.FirstOrDefault().Stereotype.Name;
```

**Comment by simonbrowndotje** [comment]
Correct, ```terminology.SoftwareSystem = "x"``` will set the terminology to ```x``` for all software systems, in all diagrams, in the workspace. There's no way to set the terminology on a case by case basis I'm afraid.

**Comment by niem94** [comment]
I see, i hoped that this would be something you would consider. It would be nice if you could let individual softwaresystems know about its terminology and overwrite it if needed. Then you could still use the default implementation, while letting the terminology set on the software system take priority over the shared value. Does this sound feasible?

**Comment by simonbrowndotje** [comment]
You can hide the metadata by setting the ```metadata``` property to false on an ```ElementStyle``` ... but supporting the ability to override the terminology on a case by case basis is not something that I want to support I'm afraid.

**Comment by niem94** [comment]
That works thank you a lot for sharing :-) I just prepended the element name with the stereotype:
![image](https://user-images.githubusercontent.com/26203420/77358882-fdb92c00-6d4a-11ea-95a6-2ce93937be1a.png)
